const SECRECT = {
  BASE_URL: import.meta.env.VITE_BASE_URL,
  CLOUDINARY_UPLOAD_PRESET: import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_NAME: import.meta.env.VITE_CLOUDINARY_NAME,
};

export default SECRECT;
